version: "3.8"

services:
  wordpress:
    image: wordpress:php7.4
    container_name: wordpress
    depends_on:
      - mysql
    environment:
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    volumes:
      - ${WORDPRESS_DIR:-./core/wordpress}:/var/www/html
    ports:
      - "8000:80"
    restart: always
    networks:
      - wordpress-network

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-no}
    volumes:
      - ${MYSQL_DIR:-./core/mysql}:/var/lib/mysql
    restart: always
    networks:
      - wordpress-network

volumes:
  mysql:
  wordpress:

networks:
  wordpress-network:
    driver: bridge
